# Generated by Django 5.2.11 on 2026-02-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubagentRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("child_session_id", models.CharField(max_length=64, unique=True)),
                ("root_session_id", models.CharField(db_index=True, max_length=64)),
                ("parent_session_id", models.CharField(db_index=True, max_length=64)),
                ("task", models.TextField()),
                ("system_prompt", models.TextField(blank=True)),
                ("status", models.CharField(default="running", max_length=20)),
                ("result_summary", models.TextField(blank=True)),
                ("started_at", models.FloatField()),
                ("completed_at", models.FloatField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubagentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seq", models.PositiveIntegerField()),
                ("role", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("tool_call_id", models.CharField(blank=True, default="", max_length=64)),
                ("tool_name", models.CharField(blank=True, default="", max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="subagents.subagentrun",
                    ),
                ),
            ],
            options={
                "ordering": ["seq"],
                "unique_together": {("run", "seq")},
            },
        ),
    ]
