# Generated by Django 5.2.11 on 2026-02-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subagents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subagentrun",
            name="input_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subagentrun",
            name="output_tokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subagentrun",
            name="total_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
