# Generated by Django 5.2.11 on 2026-02-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subagents", "0002_subagentrun_input_tokens_subagentrun_output_tokens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subagentrun",
            name="cached_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
