# Generated by Django 5.2.6 on 2026-02-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0009_message_seq_unique_response_seq"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="skills_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]

