# Generated by Django 5.2.11 on 2026-02-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_messages", "0010_session_skills_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("skill_name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("tools", models.JSONField(default=list)),
                ("depends_on", models.JSONField(default=list)),
                ("subagent_access", models.CharField(default="always", max_length=20)),
                ("source", models.CharField(default="server", max_length=20)),
                ("body", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["skill_name"],
            },
        ),
        migrations.CreateModel(
            name="ToolSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("tool_name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("parameters_schema", models.JSONField(blank=True, default=dict)),
                ("display_name", models.CharField(blank=True, default="", max_length=100)),
                ("guide", models.TextField(blank=True, default="")),
                ("source", models.CharField(default="unknown", max_length=20)),
                ("execution_target", models.CharField(default="server", max_length=20)),
                ("is_snapshot", models.BooleanField(default=False)),
                ("is_mutating", models.BooleanField(default=False)),
                ("is_read_only", models.BooleanField(default=False)),
                ("is_poll", models.BooleanField(default=False)),
                ("requires_approval", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tool_name"],
            },
        ),
    ]
