# Copyright (c) 2026 Heureum AI. All rights reserved.

"""
Plan skill — hierarchical task planning with dependency-based execution.

The agent creates a plan of tasks (each with todo items) and executes them
via sub-agents.  Tasks with dependencies wait until their predecessors
complete before spawning.
"""

import asyncio
import json
import logging
import time
import uuid
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Literal, Optional

from pydantic import BaseModel, Field

from app.config import settings

logger = logging.getLogger(__name__)

# Module-level config — injected via PlanSkill.on_init from app.config.settings
_config: Dict[str, Any] = {
    "max_spawn_depth": 2,
    "max_children": 5,
}

# ---------------------------------------------------------------------------
# Structured output schemas (Pydantic)
# ---------------------------------------------------------------------------


class PlannerTask(BaseModel):
    """Individual task structure generated by the planner."""

    id: str
    description: str
    category: Literal["research", "analysis", "synthesis", "verification"]
    depends_on: list[str] = Field(default_factory=list)
    todo_items: list[str] = Field(default_factory=list)


class PlannerOutput(BaseModel):
    """Structured output from the planner sub-agent."""

    goal: str
    query_analysis: str  # Query analysis — identify information categories
    tasks: list[PlannerTask]
    execution_strategy: str  # Parallelization/sequential strategy summary


class OrchestratorResult(BaseModel):
    """Final aggregated result from the orchestrator."""

    goal: str
    summary: str  # Aggregated result (passed to main agent)
    task_results: list[dict] = Field(default_factory=list)
    total_tasks: int = 0
    completed_tasks: int = 0
    failed_tasks: int = 0


# ---------------------------------------------------------------------------
# Tool schemas
# ---------------------------------------------------------------------------

MANAGE_TODO_TOOL_SCHEMA = {
    "type": "function",
    "display_name": "Todo",
    "function": {
        "name": "manage_todo",
        "description": (
            "Create or update a hierarchical task plan with dependency-based execution. "
            "When creating a plan, follow this framework:\n"
            "1. Categorize tasks: 'research' (information gathering), 'analysis' (data processing), "
            "'synthesis' (combining results), 'verification' (fact-checking)\n"
            "2. Define clear dependencies — tasks that can run in parallel should have no deps\n"
            "3. Always include a final synthesis task that depends on all research/analysis tasks\n"
            "4. Keep tasks atomic — each should be completable by a single sub-agent"
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string",
                    "enum": ["create", "update_task", "add_tasks", "thinking_checkpoint"],
                    "description": "Action to perform",
                },
                "goal": {
                    "type": "string",
                    "description": "Overall goal description (required for 'create')",
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "string",
                                "description": "Unique task identifier (e.g. 'economy', 'task_0')",
                            },
                            "description": {
                                "type": "string",
                                "description": "Task description",
                            },
                            "depends_on": {
                                "type": "array",
                                "items": {"type": "string"},
                                "description": "IDs of tasks that must complete before this one",
                            },
                            "todo_items": {
                                "type": "array",
                                "items": {"type": "string"},
                                "description": "Checklist items within this task",
                            },
                        },
                        "required": ["id", "description"],
                    },
                    "description": "Task definitions (required for 'create' and 'add_tasks')",
                },
                "task_id": {
                    "type": "string",
                    "description": "ID of task to update (required for 'update_task')",
                },
                "status": {
                    "type": "string",
                    "enum": ["in_progress", "completed", "failed"],
                    "description": "New status for the task (required for 'update_task')",
                },
                "result": {
                    "type": "string",
                    "description": "Brief result description for completed/failed tasks",
                },
                "phase": {
                    "type": "string",
                    "enum": ["pre_plan", "post_plan"],
                    "description": "Checkpoint phase (required when action='thinking_checkpoint')",
                },
                "note": {
                    "type": "string",
                    "description": "Reflection note for the checkpoint",
                },
            },
            "required": ["action"],
        },
    },
}

SESSIONS_SPAWN_TOOL_SCHEMA = {
    "type": "function",
    "display_name": "Sub-Agent",
    "function": {
        "name": "sessions_spawn",
        "description": (
            "Spawn a sub-agent to handle a self-contained task in parallel. "
            "The sub-agent runs independently with its own context and tools, "
            "and reports back when done. Use this for tasks that can be "
            "delegated without needing real-time interaction. "
            "Use depends_on to pass results from completed sub-agents as context."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "task": {
                    "type": "string",
                    "description": "A clear, self-contained description of the task for the sub-agent.",
                },
                "skills": {
                    "type": "array",
                    "items": {"type": "string"},
                    "maxItems": 2,
                    "description": (
                        "Skills to assign to the sub-agent. The sub-agent can ONLY use "
                        "tools defined in these skills. Example: ['web_search_task']"
                    ),
                },
                "tools": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Optional list of tool names the sub-agent should have access to. Defaults to all available tools.",
                },
                "depends_on": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": (
                        "Optional list of child_session_ids of previously completed sub-agents. "
                        "Their result summaries will be injected into this sub-agent's context, "
                        "enabling data chaining between sequential sub-agents."
                    ),
                },
                "cleanup": {
                    "type": "string",
                    "enum": ["keep", "delete"],
                    "description": "Whether to keep or delete the sub-agent session after completion. Defaults to 'delete'.",
                },
            },
            "required": ["task", "skills"],
        },
    },
}

SESSIONS_SPAWN_STATUS_TOOL_SCHEMA = {
    "type": "function",
    "display_name": "Sub-Agent Status",
    "function": {
        "name": "sessions_spawn_status",
        "description": (
            "Check the status of spawned sub-agents. "
            "Returns status, elapsed time, and result summary for each sub-agent. "
            "Call with no arguments to list all sub-agents for the current session, "
            "or provide a child_session_id to check a specific one."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "child_session_id": {
                    "type": "string",
                    "description": "Optional. ID of a specific sub-agent to check. If omitted, returns all sub-agents for this session.",
                },
            },
        },
    },
}

# ---------------------------------------------------------------------------
# Sub-agent data models (moved from app.services.subagent)
# ---------------------------------------------------------------------------


@dataclass
class ProgressStep:
    """A single tool call progress entry within a sub-agent run."""

    tool_name: str
    display_name: str
    detail: str
    status: str = "running"  # "running" | "completed" | "failed"
    started_at: float = field(default_factory=time.time)
    completed_at: Optional[float] = None


@dataclass
class SpawnRequest:
    """Request to spawn a sub-agent."""

    parent_session_id: str
    task: str
    tools: Optional[List[str]] = None
    skills: Optional[List[str]] = None  # PSA skill names inherited from parent
    cleanup: str = "delete"  # "keep" or "delete"
    skills_prompt: Optional[str] = None


@dataclass
class SpawnResult:
    """Result from a spawn attempt."""

    status: str  # "accepted", "forbidden", "error"
    child_session_id: str = ""
    message: str = ""


@dataclass
class SubagentRunRecord:
    """Tracks a single sub-agent run."""

    child_session_id: str
    parent_session_id: str
    task: str
    root_session_id: str = ""  # root session for global limit tracking
    status: str = "running"  # "running", "completed", "failed", "timeout"
    started_at: float = field(default_factory=time.time)
    completed_at: Optional[float] = None
    result_summary: str = ""
    asyncio_task: Optional[asyncio.Task] = None
    progress_log: List[ProgressStep] = field(default_factory=list)
    current_iteration: int = 0


# ---------------------------------------------------------------------------
# Registry (moved from app.services.subagent)
# ---------------------------------------------------------------------------


class SubagentRegistry:
    """Tracks active and completed sub-agent runs."""

    # Completed records older than this are eligible for GC.
    STALE_TTL_SECONDS: float = 600  # 10 minutes

    def __init__(self) -> None:
        self._runs: Dict[str, SubagentRunRecord] = {}

    def register(self, record: SubagentRunRecord) -> None:
        self._runs[record.child_session_id] = record

    def get(self, child_session_id: str) -> Optional[SubagentRunRecord]:
        return self._runs.get(child_session_id)

    def count_active(self, parent_session_id: str) -> int:
        return sum(
            1
            for r in self._runs.values()
            if r.parent_session_id == parent_session_id and r.status == "running"
        )

    def mark_completed(
        self,
        child_session_id: str,
        status: str = "completed",
        summary: str = "",
    ) -> None:
        record = self._runs.get(child_session_id)
        if record:
            record.status = status
            record.completed_at = time.time()
            record.result_summary = summary

    def count_by_root(self, root_session_id: str) -> int:
        """Count all sub-agents (running + completed) under a root session."""
        return sum(
            1 for r in self._runs.values()
            if r.root_session_id == root_session_id
        )

    def list_by_parent(self, parent_session_id: str) -> List[SubagentRunRecord]:
        """Return all runs (active and completed) for a parent session."""
        return [r for r in self._runs.values() if r.parent_session_id == parent_session_id]

    def cleanup(self, child_session_id: str) -> None:
        self._runs.pop(child_session_id, None)

    def sweep_stale(self) -> List[str]:
        """Remove completed/failed/timeout records older than STALE_TTL_SECONDS.

        Returns the list of swept child_session_ids.
        Caller is responsible for cleaning up associated depth tracking
        and shared service state.
        """
        now = time.time()
        stale_ids: List[str] = []
        for sid, record in list(self._runs.items()):
            if record.status == "running":
                continue
            completed_at = record.completed_at or record.started_at
            if now - completed_at > self.STALE_TTL_SECONDS:
                stale_ids.append(sid)

        for sid in stale_ids:
            self._runs.pop(sid, None)

        if stale_ids:
            logger.info("Swept %d stale subagent records: %s", len(stale_ids), stale_ids)
        return stale_ids


# Module-level singleton
_registry = SubagentRegistry()


def get_registry() -> SubagentRegistry:
    return _registry


# ---------------------------------------------------------------------------
# Depth tracking (moved from app.services.subagent)
# ---------------------------------------------------------------------------

_session_depth: Dict[str, int] = {}


def get_subagent_depth(session_id: str) -> int:
    """Get the spawn depth of a session (0 = root)."""
    return _session_depth.get(session_id, 0)


def _set_child_depth(child_session_id: str, parent_session_id: str) -> None:
    """Set child depth = parent depth + 1."""
    parent_depth = get_subagent_depth(parent_session_id)
    _session_depth[child_session_id] = parent_depth + 1


def _clear_depth(session_id: str) -> None:
    """Remove depth tracking for a session."""
    _session_depth.pop(session_id, None)


# ---------------------------------------------------------------------------
# Orchestration (moved from app.services.subagent)
# ---------------------------------------------------------------------------


def _resolve_root_session(parent_session_id: str) -> str:
    """Walk up the registry to find the root (non-subagent) session ID."""
    current = parent_session_id
    for _ in range(10):  # safety limit
        record = _registry.get(current)
        if record is None:
            break
        current = record.parent_session_id
    return current


async def spawn_subagent(request: SpawnRequest, create_task_fn: Any) -> SpawnResult:
    """Spawn a sub-agent task.

    Validates depth and children limits, then creates an async task
    for the sub-agent execution.

    Args:
        request: The spawn request with task description and config.
        create_task_fn: Callable(record, request, registry, clear_depth_fn) -> asyncio.Task

    Returns:
        SpawnResult with status and child session ID.
    """
    # Depth check
    max_depth = _config["max_spawn_depth"]
    depth = get_subagent_depth(request.parent_session_id)
    if depth >= max_depth:
        return SpawnResult(
            status="forbidden",
            message=f"Maximum spawn depth ({max_depth}) reached. "
            "Sub-agents cannot spawn their own sub-agents.",
        )

    # Global sub-agent limit (root session scope)
    max_total = _config.get("max_total_subagents", 15)
    root_sid = _resolve_root_session(request.parent_session_id)
    total = _registry.count_by_root(root_sid)
    if total >= max_total:
        return SpawnResult(
            status="forbidden",
            message=f"Maximum total sub-agents ({max_total}) reached for this session.",
        )

    # Children limit check
    max_children = _config["max_children"]
    active = _registry.count_active(request.parent_session_id)
    if active >= max_children:
        return SpawnResult(
            status="forbidden",
            message=f"Maximum concurrent children ({max_children}) reached.",
        )

    # Create child session
    child_session_id = f"subagent_{uuid.uuid4().hex[:12]}"
    _set_child_depth(child_session_id, request.parent_session_id)

    record = SubagentRunRecord(
        child_session_id=child_session_id,
        parent_session_id=request.parent_session_id,
        task=request.task,
        root_session_id=root_sid,
    )
    _registry.register(record)

    # Launch async task
    task = create_task_fn(record, request, _registry, _clear_depth)
    record.asyncio_task = task

    logger.info(
        "Spawned sub-agent %s for parent %s (depth=%d, task=%s)",
        child_session_id,
        request.parent_session_id,
        depth + 1,
        request.task[:100],
    )

    return SpawnResult(
        status="accepted",
        child_session_id=child_session_id,
        message="Sub-agent spawned. It will report back when done.",
    )


async def await_active_subagents(
    parent_session_id: str,
    timeout: float = 300.0,
    poll_interval: float = 1.0,
) -> List[SubagentRunRecord]:
    """Wait for all active sub-agents of a parent session to complete.

    Gathers the asyncio tasks for all running sub-agents and awaits them
    with a timeout.  Returns the list of (now-completed) records.

    Args:
        parent_session_id: The parent session to wait for.
        timeout: Maximum seconds to wait (default: 5 minutes).
        poll_interval: Not used directly — asyncio.wait handles timing.

    Returns:
        List of SubagentRunRecord that were active (now completed/failed/timeout).
    """
    records = _registry.list_by_parent(parent_session_id)
    active = [r for r in records if r.status == "running" and r.asyncio_task is not None]

    if not active:
        return []

    tasks = [r.asyncio_task for r in active if r.asyncio_task is not None]

    try:
        done, pending = await asyncio.wait(tasks, timeout=timeout)
        if pending:
            logger.warning(
                "await_active_subagents: %d sub-agent(s) still pending after %.1fs timeout for parent %s",
                len(pending), timeout, parent_session_id,
            )
    except Exception:
        logger.warning(
            "Error awaiting sub-agents for parent %s",
            parent_session_id,
            exc_info=True,
        )

    return active


# ---------------------------------------------------------------------------
# Plan data models
# ---------------------------------------------------------------------------


@dataclass
class TodoItem:
    """A single checklist item within a task."""

    description: str
    status: str = "pending"  # pending | in_progress | completed | failed
    result: Optional[str] = None


@dataclass
class PlanTask:
    """A task in the execution plan with optional dependencies."""

    id: str
    description: str
    todo_items: List[TodoItem] = field(default_factory=list)
    depends_on: List[str] = field(default_factory=list)
    status: str = "pending"  # pending | blocked | in_progress | completed | failed
    child_session_id: Optional[str] = None
    result: Optional[str] = None

    @property
    def is_terminal(self) -> bool:
        return self.status in ("completed", "failed")


@dataclass
class SessionPlan:
    """A hierarchical execution plan for a session."""

    goal: str
    tasks: Dict[str, PlanTask] = field(default_factory=dict)
    phase: str = "awaiting_pre_thinking"
    # phases: awaiting_pre_thinking → executing → ready_for_final → finalized
    created_at: float = field(default_factory=time.time)
    updated_at: float = field(default_factory=time.time)

    def get_ready_tasks(self) -> List[PlanTask]:
        """Return pending tasks whose dependencies are all completed."""
        ready = []
        for task in self.tasks.values():
            if task.status != "pending":
                continue
            if all(self.tasks[dep].status == "completed" for dep in task.depends_on):
                ready.append(task)
        return ready

    def all_terminal(self) -> bool:
        """True when every task is completed or failed."""
        return all(t.is_terminal for t in self.tasks.values())


# ---------------------------------------------------------------------------
# PlanHandoffController
# ---------------------------------------------------------------------------


class PlanHandoffController:
    """Manage agent-to-agent handoffs within the plan_task pipeline.

    Handoff points:
      1. main -> planner: activate_skill triggers planner sub-agent spawn
      2. planner -> orchestrator: structured plan -> orchestrator spawn
      3. orchestrator -> main: final synthesis -> inject into main agent context
    """

    def __init__(self) -> None:
        self._create_subagent_task_fn: Any = None
        self._get_skills_prompt: Any = None
        self._skill_controller: Any = None

    def set_dependencies(self, **kwargs: Any) -> None:
        """Propagate dependencies from PlanSkill.on_init()."""
        for key in ("create_subagent_task_fn", "get_skills_prompt", "skill_controller"):
            val = kwargs.get(key)
            if val is not None:
                setattr(self, f"_{key}", val)

    async def main_to_planner(
        self, task: str, session_id: str, skills_prompt: str | None = None,
    ) -> SpawnResult:
        """Main -> Planner: spawn planner sub-agent.

        Planner uses manage_todo only to produce a structured plan.
        Synchronous wait (spawn + await) — result feeds orchestrator handoff.
        """
        planner_instruction = self._build_planner_instruction(task)
        request = SpawnRequest(
            parent_session_id=session_id,
            task=planner_instruction,
            tools=["manage_todo"],
            skills_prompt=skills_prompt,
        )
        return await spawn_subagent(request, self._create_subagent_task_fn)

    async def planner_to_orchestrator(
        self, plan: SessionPlan, session_id: str, skills_prompt: str | None = None,
    ) -> SpawnResult:
        """Planner -> Orchestrator: spawn orchestrator from structured plan.

        Orchestrator uses sessions_spawn + manage_todo + available MCP tools.
        Async execution — leaf completion managed via cascade loop.
        """
        parent_skills = self._get_parent_skills(session_id)
        orchestrator_instruction = self._build_orchestrator_instruction(plan)
        request = SpawnRequest(
            parent_session_id=session_id,
            task=orchestrator_instruction,
            skills=parent_skills,
            skills_prompt=skills_prompt,
        )
        return await spawn_subagent(request, self._create_subagent_task_fn)

    async def orchestrator_to_main(
        self, record: Any, synthesis: str
    ) -> str:
        """Orchestrator -> Main: inject final result into main agent context.

        Leverages existing _announce_completion() pattern — SystemMessage to parent.
        """
        from app.services.subagent import _announce_completion

        await _announce_completion(record, synthesis)
        return synthesis

    def _build_planner_instruction(self, task: str) -> str:
        """Planner-specific prompt — systematic plan creation."""
        return (
            "You are a planning agent. Analyze the user's request and create "
            "a structured execution plan.\n\n"
            f"## User Request\n{task}\n\n"
            "## Planning Framework\n"
            "1. **Query Analysis**: Identify information categories needed\n"
            "2. **Task Decomposition**: Break into concrete, atomic tasks\n"
            "3. **Categorize**: Each task = research | analysis | synthesis | verification\n"
            "4. **Dependencies**: Define execution order (parallel where possible)\n"
            "5. **Verification**: Include at least one verification task\n\n"
            "## Rules\n"
            "- Do NOT execute tasks — only plan them\n"
            "- Each task must be self-contained (executable by an independent agent)\n"
            "- Always include a final synthesis task that depends on all others\n"
            "- Use manage_todo(action='create') to output your plan\n"
            "- Use manage_todo(action='thinking_checkpoint', phase='pre_plan') when done"
        )

    def _build_orchestrator_instruction(self, plan: SessionPlan) -> str:
        """Orchestrator-specific prompt — plan execution management."""
        task_list = []
        for tid, task in plan.tasks.items():
            deps = f" (depends: {', '.join(task.depends_on)})" if task.depends_on else ""
            task_list.append(f"  - [{tid}] {task.description}{deps}")
        tasks_str = "\n".join(task_list)
        return (
            "You are an orchestrator agent. Execute the following plan by "
            "spawning sub-agents for each task.\n\n"
            f"## Goal\n{plan.goal}\n\n"
            f"## Tasks\n{tasks_str}\n\n"
            "## Workflow\n"
            "1. Spawn sub-agents for tasks with no dependencies (parallel)\n"
            "2. Monitor completion via sessions_spawn_status\n"
            "3. When dependencies resolve, spawn dependent tasks\n"
            "4. After ALL tasks complete, synthesize results into a final summary\n\n"
            "## Rules\n"
            "- Use sessions_spawn to delegate each task\n"
            "- Respect dependency order — do not spawn blocked tasks\n"
            "- Final summary must be comprehensive and directly answer the user's request"
        )

    def _get_parent_skills(self, session_id: str) -> list[str] | None:
        if not self._skill_controller:
            return None
        try:
            names = self._skill_controller.get_active_skill_names(session_id)
            return list(names) if names else None
        except Exception:
            return None


# ---------------------------------------------------------------------------
# SessionsSpawnSkill
# ---------------------------------------------------------------------------


class SessionsSpawnSkill:
    """Skill for spawning and tracking sub-agent tasks."""

    name = "sessions_spawn"
    tool_schemas = [SESSIONS_SPAWN_TOOL_SCHEMA]

    def __init__(self) -> None:
        self._create_subagent_task_fn: Any = None
        self._get_skills_prompt: Any = None
        self._skill_controller: Any = None

    def set_dependencies(
        self,
        *,
        create_subagent_task_fn: Any = None,
        get_skills_prompt: Any = None,
        skill_controller: Any = None,
    ) -> None:
        """Inject runtime dependencies (called by PlanSkill.on_init)."""
        if create_subagent_task_fn is not None:
            self._create_subagent_task_fn = create_subagent_task_fn
        if get_skills_prompt is not None:
            self._get_skills_prompt = get_skills_prompt
        if skill_controller is not None:
            self._skill_controller = skill_controller

    def has_unfinished_steps(self, session_id: str) -> bool:
        try:
            return _registry.count_active(session_id) > 0
        except Exception:
            return False

    def build_retry_guidance(self, session_id: str, abandoned_text: str) -> str:
        try:
            records = _registry.list_by_parent(session_id)

            active = [r for r in records if r.status == "running"]
            completed = [r for r in records if r.status in ("completed", "failed", "timeout")]

            parts = [
                "Sub-agents are still running. DO NOT respond to the user yet.",
                "Wait for all sub-agents to complete, then synthesize their results.",
            ]

            if completed:
                parts.append("\nCompleted sub-agents:")
                for r in completed:
                    summary = r.result_summary[:200] if r.result_summary else "No result"
                    parts.append(f"  - [{r.status}] {r.task[:100]}: {summary}")

            if active:
                parts.append(f"\nStill running: {len(active)} sub-agent(s)")
                for r in active:
                    parts.append(f"  - {r.task[:100]} (iteration {r.current_iteration})")

            return "\n".join(parts)
        except Exception:
            return "Sub-agents are still running. Wait for them to complete before responding."

    async def await_pending(self, session_id: str, timeout: float = 300.0) -> None:
        try:
            await await_active_subagents(session_id, timeout=timeout)
        except Exception:
            logger.warning("await_pending failed for session %s", session_id, exc_info=True)

    async def execute(self, name: str, args: Dict[str, Any], session_id: str) -> str:
        if name == "sessions_spawn":
            return await self._spawn(args, session_id)
        if name == "sessions_spawn_status":
            return await self._status(args, session_id)
        return json.dumps({"error": f"Unknown tool: {name}"})

    def _get_parent_skills(self, session_id: str) -> Optional[List[str]]:
        """Resolve active PSA skill names from the parent session."""
        if not self._skill_controller:
            return None
        try:
            names = self._skill_controller.get_active_skill_names(session_id)
            return list(names) if names else None
        except Exception:
            return None

    def _resolve_depends_on(self, depends_on: list[str], session_id: str) -> str:
        """Resolve predecessor sub-agent results for data chaining.

        Looks up each child_session_id in the registry and collects their
        result summaries. Returns a formatted context block to prepend to
        the sub-agent's task description.
        """
        if not depends_on:
            return ""
        parts: list[str] = []
        for child_id in depends_on:
            record = _registry.get(child_id)
            if not record:
                continue
            if record.parent_session_id != session_id:
                continue
            if record.status not in ("completed", "failed", "timeout"):
                continue
            summary = record.result_summary
            if summary:
                parts.append(
                    f"### Result from previous sub-agent ({child_id})\n"
                    f"Task: {record.task[:200]}\n"
                    f"{summary[:4000]}"
                )
        if not parts:
            return ""
        return "## Context from predecessor sub-agents\n\n" + "\n\n".join(parts) + "\n\n---\n\n"

    async def _spawn(self, args: Dict[str, Any], session_id: str) -> str:
        try:
            task = (args.get("task") or "").strip()
            if not task:
                return json.dumps({"error": "task is required. Provide a clear task description."})

            # Resolve predecessor results for data chaining
            depends_on = args.get("depends_on") or []
            predecessor_context = self._resolve_depends_on(depends_on, session_id)
            if predecessor_context:
                task = predecessor_context + task

            parent_skills_prompt = None
            if self._get_skills_prompt:
                try:
                    parent_skills_prompt = self._get_skills_prompt()
                except Exception:
                    pass

            # Orchestrator-specified skills take priority, fallback to parent skills
            child_skills = args.get("skills") or self._get_parent_skills(session_id)

            request = SpawnRequest(
                parent_session_id=session_id,
                task=task,
                tools=args.get("tools"),
                skills=child_skills,
                cleanup=args.get("cleanup", "delete"),
                skills_prompt=parent_skills_prompt,
            )
            result = await spawn_subagent(request, self._create_subagent_task_fn)
            return json.dumps(
                {
                    "status": result.status,
                    "child_session_id": result.child_session_id,
                    "message": result.message,
                }
            )
        except Exception as e:
            logger.warning("Sub-agent spawn failed: %s", e)
            return json.dumps({"error": str(e)})

    async def _status(self, args: Dict[str, Any], session_id: str) -> str:
        try:
            child_id = args.get("child_session_id")

            if child_id:
                record = _registry.get(child_id)
                if not record:
                    return json.dumps({"error": f"Sub-agent '{child_id}' not found"})
                if record.parent_session_id != session_id:
                    return json.dumps({"error": f"Sub-agent '{child_id}' not found"})
                return json.dumps(self._record_to_dict(record))

            records = _registry.list_by_parent(session_id)
            if not records:
                return json.dumps(
                    {"message": "No sub-agents found for this session", "children": []}
                )

            return json.dumps({"children": [self._record_to_dict(r) for r in records]})
        except Exception as e:
            logger.warning("Sub-agent status check failed: %s", e)
            return json.dumps({"error": str(e)})

    @staticmethod
    def _record_to_dict(record) -> Dict[str, Any]:
        elapsed = time.time() - record.started_at
        result: Dict[str, Any] = {
            "child_session_id": record.child_session_id,
            "task": record.task[:settings.SUBAGENT_STATUS_TASK_MAXLEN],
            "status": record.status,
            "elapsed_seconds": round(elapsed, 1),
        }
        if record.result_summary:
            result["result_summary"] = record.result_summary[:settings.SUBAGENT_STATUS_RESULT_MAXLEN]
        return result


# ---------------------------------------------------------------------------
# PlanSkill
# ---------------------------------------------------------------------------


class PlanSkill:
    """Manages hierarchical task plans with dependency-based execution."""

    name = "plan_task"
    tool_schemas = [
        MANAGE_TODO_TOOL_SCHEMA,
        SESSIONS_SPAWN_TOOL_SCHEMA,
        SESSIONS_SPAWN_STATUS_TOOL_SCHEMA,
    ]

    def __init__(self) -> None:
        self._session_plans: Dict[str, SessionPlan] = {}
        self._session_history: Dict[str, List[SessionPlan]] = {}
        self._create_subagent_task_fn: Any = None
        self._get_skills_prompt: Any = None
        self._skill_controller: Any = None
        self._spawn_skill = SessionsSpawnSkill()
        self._handoff = PlanHandoffController()

    async def on_init(self, **kwargs: Any) -> None:
        create_subagent_task_fn = kwargs.get("create_subagent_task_fn")
        if create_subagent_task_fn is not None:
            self._create_subagent_task_fn = create_subagent_task_fn
        get_skills_prompt = kwargs.get("get_skills_prompt")
        if get_skills_prompt is not None:
            self._get_skills_prompt = get_skills_prompt
        skill_controller = kwargs.get("skill_controller")
        if skill_controller is not None:
            self._skill_controller = skill_controller
        # Inject config (max_spawn_depth, max_children, etc.)
        subagent_config = kwargs.get("subagent_config")
        if subagent_config:
            _config.update(subagent_config)
        # Patch schema maxItems from config
        skills_prop = SESSIONS_SPAWN_TOOL_SCHEMA["function"]["parameters"]["properties"].get("skills")
        if skills_prop and subagent_config:
            skills_prop["maxItems"] = subagent_config.get("max_skills", settings.SUBAGENT_MAX_SKILLS)
        # Propagate dependencies to spawn sub-skill
        self._spawn_skill.set_dependencies(
            create_subagent_task_fn=self._create_subagent_task_fn,
            get_skills_prompt=self._get_skills_prompt,
            skill_controller=self._skill_controller,
        )
        # Propagate dependencies to handoff controller
        self._handoff.set_dependencies(
            create_subagent_task_fn=self._create_subagent_task_fn,
            get_skills_prompt=self._get_skills_prompt,
            skill_controller=self._skill_controller,
        )

    async def execute(self, name: str, arguments: Dict[str, Any], session_id: str) -> str:
        # Delegate spawn tools to SessionsSpawnSkill
        if name in ("sessions_spawn", "sessions_spawn_status"):
            return await self._spawn_skill.execute(name, arguments, session_id)

        action = arguments.get("action", "")
        if action == "create":
            return await self._create(
                session_id,
                arguments.get("goal", ""),
                arguments.get("tasks", []),
            )
        elif action == "update_task":
            return await self._update_task(
                session_id,
                arguments.get("task_id", ""),
                arguments.get("status", "completed"),
                arguments.get("result"),
            )
        elif action == "add_tasks":
            return await self._add_tasks(
                session_id,
                arguments.get("tasks", []),
            )
        elif action == "thinking_checkpoint":
            return await self._thinking_checkpoint(
                session_id,
                arguments.get("phase", ""),
                arguments.get("note", ""),
            )
        else:
            return f"Unknown action: {action}"

    # ------------------------------------------------------------------
    # Thinking checkpoint
    # ------------------------------------------------------------------

    async def _thinking_checkpoint(self, session_id: str, phase: str, note: str) -> str:
        plan = self._session_plans.get(session_id)
        if not plan:
            return "Error: no active plan"
        if phase == "pre_plan":
            if plan.phase != "awaiting_pre_thinking":
                return f"Error: pre checkpoint not expected in phase '{plan.phase}'"
            plan.phase = "executing"
            plan.updated_at = time.time()
            await self._spawn_ready_tasks(session_id, plan)
            return self._format_state(plan)
        elif phase == "post_plan":
            if plan.phase != "ready_for_final":
                return f"Error: post checkpoint not expected in phase '{plan.phase}'"
            plan.phase = "finalized"
            plan.updated_at = time.time()
            return self._format_state(plan)
        return f"Error: unknown phase '{phase}'"

    # ------------------------------------------------------------------
    # Plan creation
    # ------------------------------------------------------------------

    @staticmethod
    def _has_cycle(tasks: Dict[str, PlanTask]) -> bool:
        """DFS cycle detection on the dependency graph."""
        WHITE, GRAY, BLACK = 0, 1, 2
        color: Dict[str, int] = {tid: WHITE for tid in tasks}

        def dfs(tid: str) -> bool:
            color[tid] = GRAY
            for dep in tasks[tid].depends_on:
                if dep not in color:
                    continue
                if color[dep] == GRAY:
                    return True
                if color[dep] == WHITE and dfs(dep):
                    return True
            color[tid] = BLACK
            return False

        return any(dfs(tid) for tid, c in color.items() if c == WHITE)

    async def _create(self, session_id: str, goal: str, raw_tasks: List[Dict[str, Any]]) -> str:
        if not goal:
            return "Error: goal description is required"
        if not raw_tasks:
            return "Error: at least one task is required"

        # Build PlanTask objects
        tasks: Dict[str, PlanTask] = {}
        seen_ids: set = set()
        for t in raw_tasks:
            tid = t.get("id", "")
            if not tid:
                return "Error: every task must have an 'id'"
            if tid in seen_ids:
                return f"Error: duplicate task id '{tid}'"
            seen_ids.add(tid)

            todo_items = [TodoItem(description=d) for d in (t.get("todo_items") or [])]
            depends_on = t.get("depends_on") or []
            tasks[tid] = PlanTask(
                id=tid,
                description=t.get("description", ""),
                todo_items=todo_items,
                depends_on=depends_on,
            )

        # Validate dependency references
        for task in tasks.values():
            for dep in task.depends_on:
                if dep not in tasks:
                    return f"Error: task '{task.id}' depends on unknown task '{dep}'"

        # Cycle check
        if self._has_cycle(tasks):
            return "Error: circular dependency detected in tasks"

        # Set initial statuses: blocked if has deps, pending otherwise
        for task in tasks.values():
            if task.depends_on:
                task.status = "blocked"
            else:
                task.status = "pending"

        # Archive existing plan
        existing = self._session_plans.get(session_id)
        if existing:
            self._session_history.setdefault(session_id, []).append(existing)

        plan = SessionPlan(goal=goal, tasks=tasks)
        self._session_plans[session_id] = plan

        # Phase = awaiting_pre_thinking — spawn deferred until pre checkpoint
        return self._format_state(plan)

    # ------------------------------------------------------------------
    # Task spawning
    # ------------------------------------------------------------------

    def _get_parent_skills(self, session_id: str) -> Optional[List[str]]:
        """Resolve active PSA skill names from the parent session."""
        if not self._skill_controller:
            return None
        try:
            names = self._skill_controller.get_active_skill_names(session_id)
            return list(names) if names else None
        except Exception:
            return None

    async def _spawn_ready_tasks(self, session_id: str, plan: SessionPlan) -> None:
        """Spawn sub-agents for all ready (pending, deps satisfied) tasks."""
        if plan.phase == "awaiting_pre_thinking":
            return  # pre checkpoint 전 spawn 금지
        ready = plan.get_ready_tasks()
        if not ready:
            return

        skills_prompt = None
        if self._get_skills_prompt:
            try:
                skills_prompt = self._get_skills_prompt()
            except Exception:
                pass

        parent_skills = self._get_parent_skills(session_id)

        max_children = _config["max_children"]
        active_count = _registry.count_active(session_id)

        for task in ready:
            if active_count >= max_children:
                break

            # Build task instruction
            instruction_parts = [f"Goal: {plan.goal}", f"Task: {task.description}"]
            if task.todo_items:
                instruction_parts.append("Checklist:")
                for item in task.todo_items:
                    instruction_parts.append(f"  - {item.description}")

            # Include completed dependency results for context
            dep_results = []
            for dep_id in task.depends_on:
                dep_task = plan.tasks.get(dep_id)
                if dep_task and dep_task.result:
                    dep_results.append(f"[{dep_id}] {dep_task.result}")
            if dep_results:
                instruction_parts.append("\nPrevious task results:")
                instruction_parts.extend(f"  {r}" for r in dep_results)

            instruction = "\n".join(instruction_parts)

            task.status = "in_progress"
            try:
                result = await spawn_subagent(
                    SpawnRequest(
                        parent_session_id=session_id,
                        task=instruction,
                        skills=parent_skills,
                        skills_prompt=skills_prompt,
                    ),
                    self._create_subagent_task_fn,
                )
                if result.status == "accepted":
                    task.child_session_id = result.child_session_id
                    active_count += 1
                else:
                    task.status = "failed"
                    task.result = result.message
            except Exception as e:
                task.status = "failed"
                task.result = str(e)

        plan.updated_at = time.time()

    # ------------------------------------------------------------------
    # Status sync from sub-agent registry
    # ------------------------------------------------------------------

    def _sync_task_statuses(self, session_id: str, plan: SessionPlan) -> bool:
        """Sync task statuses from the sub-agent registry. Returns True if anything changed."""
        changed = False

        for task in plan.tasks.values():
            if task.child_session_id and task.status == "in_progress":
                record = _registry.get(task.child_session_id)
                if record and record.status != "running":
                    changed = True
                    if record.status == "completed":
                        task.status = "completed"
                        task.result = (record.result_summary or "Done")[:200]
                    else:
                        task.status = "failed"
                        task.result = record.result_summary or record.status

        # Promote blocked tasks whose deps are now all completed
        for task in plan.tasks.values():
            if task.status == "blocked":
                deps_ok = all(plan.tasks[dep].status == "completed" for dep in task.depends_on)
                deps_failed = any(plan.tasks[dep].status == "failed" for dep in task.depends_on)
                if deps_failed:
                    task.status = "failed"
                    task.result = "Dependency failed"
                    changed = True
                elif deps_ok:
                    task.status = "pending"
                    changed = True

        if changed:
            plan.updated_at = time.time()
        return changed

    # ------------------------------------------------------------------
    # await_pending — cascade loop
    # ------------------------------------------------------------------

    async def await_pending(self, session_id: str, timeout: float = 300.0) -> None:
        """Wait for sub-agents, sync statuses, and cascade to newly ready tasks."""
        plan = self._session_plans.get(session_id)
        if not plan:
            return

        while True:
            # 1. Wait for current sub-agents
            try:
                await await_active_subagents(session_id, timeout=timeout)
            except Exception:
                logger.warning("await_pending failed for session %s", session_id, exc_info=True)
                break

            # 2. Sync statuses from registry
            self._sync_task_statuses(session_id, plan)

            # 3. Transition: all_terminal + executing → ready_for_final
            if plan.all_terminal() and plan.phase == "executing":
                plan.phase = "ready_for_final"
                plan.updated_at = time.time()

            # 4. Check for newly ready tasks
            ready = plan.get_ready_tasks()
            if not ready:
                break
            if plan.phase == "awaiting_pre_thinking":
                break  # pre checkpoint 전 spawn 금지

            # 5. Spawn new tasks
            await self._spawn_ready_tasks(session_id, plan)

            # 6. Loop to wait for new sub-agents

    # ------------------------------------------------------------------
    # Manual task update
    # ------------------------------------------------------------------

    async def _update_task(
        self,
        session_id: str,
        task_id: str,
        status: str,
        result: Optional[str] = None,
    ) -> str:
        plan = self._session_plans.get(session_id)
        if not plan:
            return "Error: no plan exists for this session"
        task = plan.tasks.get(task_id)
        if not task:
            return f"Error: task '{task_id}' not found"

        task.status = status
        if result is not None:
            task.result = result
        plan.updated_at = time.time()

        # Cascade: promote blocked tasks and spawn newly ready ones
        self._sync_task_statuses(session_id, plan)
        self._recalculate_phase(plan)
        await self._spawn_ready_tasks(session_id, plan)

        return self._format_state(plan)

    # ------------------------------------------------------------------
    # Add tasks to existing plan
    # ------------------------------------------------------------------

    async def _add_tasks(
        self,
        session_id: str,
        raw_tasks: List[Dict[str, Any]],
    ) -> str:
        plan = self._session_plans.get(session_id)
        if not plan:
            return "Error: no plan exists for this session"
        if not raw_tasks:
            return "Error: at least one task is required"

        for t in raw_tasks:
            tid = t.get("id", "")
            if not tid:
                return "Error: every task must have an 'id'"
            if tid in plan.tasks:
                return f"Error: task id '{tid}' already exists"

            todo_items = [TodoItem(description=d) for d in (t.get("todo_items") or [])]
            depends_on = t.get("depends_on") or []

            # Validate deps reference existing tasks
            for dep in depends_on:
                if dep not in plan.tasks:
                    return f"Error: task '{tid}' depends on unknown task '{dep}'"

            task = PlanTask(
                id=tid,
                description=t.get("description", ""),
                todo_items=todo_items,
                depends_on=depends_on,
                status="blocked" if depends_on else "pending",
            )
            plan.tasks[tid] = task

        plan.updated_at = time.time()
        self._recalculate_phase(plan)
        await self._spawn_ready_tasks(session_id, plan)
        return self._format_state(plan)

    # ------------------------------------------------------------------
    # Phase recalculation
    # ------------------------------------------------------------------

    @staticmethod
    def _recalculate_phase(plan: SessionPlan) -> None:
        """Recalculate phase after task mutations (update/add).

        Checkpoint transitions (awaiting_pre_thinking, finalized) require
        explicit thinking_checkpoint action — never auto-transition into or out of them.
        """
        if plan.phase in ("awaiting_pre_thinking", "finalized"):
            return
        if plan.all_terminal():
            plan.phase = "ready_for_final"
        else:
            plan.phase = "executing"

    # ------------------------------------------------------------------
    # State accessors
    # ------------------------------------------------------------------

    def get_state(self, session_id: str) -> Optional[SessionPlan]:
        return self._session_plans.get(session_id)

    def get_failed_step(self, session_id: str) -> Optional[PlanTask]:
        plan = self._session_plans.get(session_id)
        if not plan:
            return None
        for task in plan.tasks.values():
            if task.status == "failed":
                return task
        return None

    def is_all_complete(self, session_id: str) -> bool:
        plan = self._session_plans.get(session_id)
        if not plan:
            return False
        return plan.phase == "finalized"

    def has_unfinished_steps(self, session_id: str) -> bool:
        plan = self._session_plans.get(session_id)
        if plan and plan.phase != "finalized":
            return True
        if plan and any(
            t.status in ("in_progress", "pending", "blocked") for t in plan.tasks.values()
        ):
            return True
        return self._spawn_skill.has_unfinished_steps(session_id)

    # ------------------------------------------------------------------
    # Retry guidance
    # ------------------------------------------------------------------

    def build_retry_guidance(self, session_id: str, abandoned_text: str) -> Optional[str]:
        plan = self._session_plans.get(session_id)
        if not plan:
            return None

        # Phase-specific checkpoint guidance (takes priority)
        if plan.phase == "awaiting_pre_thinking":
            return (
                "Call manage_todo(action='thinking_checkpoint', phase='pre_plan', "
                "note='<your review>') to begin execution."
            )
        if plan.phase == "ready_for_final":
            return (
                "All tasks completed. Call manage_todo(action='thinking_checkpoint', "
                "phase='post_plan', note='<your verification>') before final summary."
            )

        in_progress = []
        pending = []
        blocked = []
        completed = []
        failed = []
        for task in plan.tasks.values():
            if task.status == "in_progress":
                in_progress.append(task)
            elif task.status == "pending":
                pending.append(task)
            elif task.status == "blocked":
                blocked.append(task)
            elif task.status == "completed":
                completed.append(task)
            elif task.status == "failed":
                failed.append(task)

        if not in_progress and not pending and not blocked:
            return None

        lines = [
            "You tried to respond without finishing the plan. "
            "You MUST complete every task before giving a final answer.",
        ]

        if completed or failed:
            lines.append("")
            lines.append("## Previous tasks")
            for t in completed:
                result_part = f" → {t.result}" if t.result else ""
                lines.append(f"  ✓ {t.id}: {t.description}{result_part}")
            for t in failed:
                result_part = f" → {t.result}" if t.result else ""
                lines.append(f"  ✗ {t.id}: {t.description}{result_part}")

        if in_progress or pending:
            running = in_progress + pending
            lines.append("")
            lines.append("## Running tasks (sub-agents)")
            for t in running:
                lines.append(f"  ⟳ {t.id}: {t.description}")
            lines.append("")
            lines.append("Sub-agents are running. Wait for them to complete.")

        if blocked:
            lines.append("")
            lines.append("## Blocked tasks")
            for t in blocked:
                waiting = ", ".join(t.depends_on)
                lines.append(f"  ⏳ {t.id}: {t.description} (waiting for: {waiting})")

        lines.append("")
        lines.append(f"Progress: {len(completed)}/{len(plan.tasks)} completed.")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Finalize abandoned
    # ------------------------------------------------------------------

    async def finalize_abandoned_steps(self, session_id: str) -> None:
        plan = self._session_plans.get(session_id)
        if not plan:
            return
        # Reject abandon during checkpoint waits
        if plan.phase in ("awaiting_pre_thinking", "ready_for_final"):
            return
        changed = False
        child_sids_to_cancel: list[str] = []
        for task in plan.tasks.values():
            if task.status == "in_progress":
                task.status = "failed"
                task.result = "Abandoned by agent"
                changed = True
                if task.child_session_id:
                    child_sids_to_cancel.append(task.child_session_id)
            elif task.status in ("pending", "blocked"):
                task.status = "failed"
                task.result = "Skipped — previous task abandoned"
                changed = True
        if changed:
            plan.updated_at = time.time()

        # Cancel sub-agent asyncio tasks and update registry
        for child_sid in child_sids_to_cancel:
            record = _registry.get(child_sid)
            if record and record.status == "running":
                if record.asyncio_task and not record.asyncio_task.done():
                    record.asyncio_task.cancel()
                _registry.mark_completed(child_sid, "failed", "Abandoned by parent agent")

        # Also cancel ad-hoc sub-agents not tracked in plan tasks
        for record in _registry.list_by_parent(session_id):
            if record.status == "running":
                if record.asyncio_task and not record.asyncio_task.done():
                    record.asyncio_task.cancel()
                _registry.mark_completed(
                    record.child_session_id, "failed", "Abandoned by parent agent"
                )

    # ------------------------------------------------------------------
    # State prompt
    # ------------------------------------------------------------------

    def get_state_prompt(self, session_id: str) -> Optional[str]:
        parts: List[str] = []

        history = self._session_history.get(session_id, [])
        if history:
            hlines = ["<previous_attempts>"]
            for h in history:
                hlines.append(f"Goal: {h.goal}")
                for task in h.tasks.values():
                    result_part = f" — {task.result}" if task.result else ""
                    hlines.append(f"  [{task.status}] {task.id}: {task.description}{result_part}")
                hlines.append("")
            hlines.append(
                "Use these past results to inform your approach. "
                "Avoid repeating strategies that failed before."
            )
            hlines.append("</previous_attempts>")
            parts.append("\n".join(hlines))

        plan = self._session_plans.get(session_id)
        if not plan:
            return parts[0] if parts else None

        lines = ["<current_plan>", f"Goal: {plan.goal}"]

        # Classify tasks by status
        completed_lines: List[str] = []
        running_lines: List[str] = []
        blocked_lines: List[str] = []
        pending_lines: List[str] = []
        failed_lines: List[str] = []

        for task in plan.tasks.values():
            result_part = f" -- {task.result}" if task.result else ""
            if task.status == "completed":
                completed_lines.append(f"  {task.id}: {task.description}{result_part}")
            elif task.status == "in_progress":
                running_lines.append(f"  {task.id}: {task.description}")
            elif task.status == "blocked":
                waiting = ", ".join(task.depends_on)
                blocked_lines.append(f"  {task.id}: {task.description} (waiting for: {waiting})")
            elif task.status == "failed":
                failed_lines.append(f"  {task.id}: [FAILED] {task.description}{result_part}")
            else:  # pending
                pending_lines.append(f"  {task.id}: {task.description}")

        if completed_lines:
            lines.append("<completed_tasks>")
            lines.extend(completed_lines)
            lines.append("</completed_tasks>")
        if running_lines:
            lines.append("<running_tasks>")
            lines.extend(running_lines)
            lines.append("</running_tasks>")
        if blocked_lines:
            lines.append("<blocked_tasks>")
            lines.extend(blocked_lines)
            lines.append("</blocked_tasks>")
        if pending_lines:
            lines.append("<pending_tasks>")
            lines.extend(pending_lines)
            lines.append("</pending_tasks>")
        if failed_lines:
            lines.append("<failed_tasks>")
            lines.extend(failed_lines)
            lines.append("</failed_tasks>")

        # Phase-based action directive
        if plan.phase == "awaiting_pre_thinking":
            lines.append(
                "\nPlan created but NOT yet executing. "
                "Review your plan, then call manage_todo(action='thinking_checkpoint', "
                "phase='pre_plan', note='<your review>') to approve and begin execution."
            )
        elif plan.phase == "executing":
            unfinished = [
                t for t in plan.tasks.values() if t.status in ("pending", "in_progress", "blocked")
            ]
            if unfinished:
                lines.append(
                    f"\n{len(unfinished)} task(s) running via sub-agents. "
                    "Wait for them to complete, then synthesize results into a final answer."
                )
            else:
                lines.append("\nAll tasks completed. Awaiting phase transition.")
        elif plan.phase == "ready_for_final":
            lines.append(
                "\nAll tasks completed. Call manage_todo(action='thinking_checkpoint', "
                "phase='post_plan', note='<your verification>') to verify results "
                "before providing the final summary."
            )
        elif plan.phase == "finalized":
            lines.append("\nPlan finalized. Provide a final summary of all results.")

        lines.append("</current_plan>")
        parts.append("\n".join(lines))
        return "\n\n".join(parts)

    # ------------------------------------------------------------------
    # Session management
    # ------------------------------------------------------------------

    def clear_session(self, session_id: str) -> None:
        self._session_plans.pop(session_id, None)
        self._session_history.pop(session_id, None)

    # ------------------------------------------------------------------
    # Markdown rendering
    # ------------------------------------------------------------------

    @staticmethod
    def render_markdown(plan: SessionPlan) -> str:
        lines = ["# TODO", "", f"**Goal**: {plan.goal}", "", "## Tasks"]
        completed = 0
        in_progress = False
        for task in plan.tasks.values():
            deps_str = ""
            if task.depends_on:
                deps_str = f" (depends on: {', '.join(task.depends_on)})"

            if task.status == "completed":
                completed += 1
                lines.append(f"- [x] **{task.id}**: ~~{task.description}~~{deps_str} ✓")
                if task.result:
                    lines.append(f"  > {task.result}")
            elif task.status == "in_progress":
                in_progress = True
                lines.append(f"- [ ] **{task.id}**: **{task.description}**{deps_str} ← in progress")
            elif task.status == "failed":
                lines.append(f"- [ ] **{task.id}**: ~~{task.description}~~{deps_str} ✗")
                if task.result:
                    lines.append(f"  > {task.result}")
            elif task.status == "blocked":
                lines.append(f"- [ ] **{task.id}**: {task.description}{deps_str} ⏳ blocked")
            else:
                lines.append(f"- [ ] **{task.id}**: {task.description}{deps_str}")

            # Render todo items
            if task.todo_items:
                for item in task.todo_items:
                    check = "x" if item.status == "completed" else " "
                    lines.append(f"  - [{check}] {item.description}")

        total = len(plan.tasks)
        if completed == total:
            status = "Completed"
        elif in_progress:
            status = "In Progress"
        else:
            status = "Pending"

        lines.extend(["", "---", f"Progress: {completed}/{total} completed | Status: {status}"])
        return "\n".join(lines)

    @staticmethod
    def _format_state(plan: SessionPlan) -> str:
        completed = sum(1 for t in plan.tasks.values() if t.status == "completed")
        return json.dumps({
            "goal": plan.goal,
            "phase": plan.phase,
            "tasks": [
                {
                    "id": t.id,
                    "description": t.description,
                    "status": t.status,
                    **({"depends_on": t.depends_on} if t.depends_on else {}),
                    **({"result": t.result} if t.result else {}),
                }
                for t in plan.tasks.values()
            ],
            "progress": f"{completed}/{len(plan.tasks)}",
        })
